name: Check task

on:
    pull_request_target:
      branches:
        - test_dir
      paths:
        - contributions/**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
  
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.event.pull_request.head.sha }}
        
        - name: Check file modifications
          run: gh pr view ${{ github.event.number }} --json files --jq '.files.[].path' | cat
          env:
            GH_TOKEN: ${{ github.token }}
          #with: 
          #  x:  ${{ github.event.number }}
        - name: Get changed files
          id: changed-files
          uses: tj-actions/changed-files@v45
  
        - name: List all changed files
          env:
            ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
            ALL_CHANGED_FILES_COUNT: ${{ steps.changed-files.outputs.all_changed_files_count }}
          run: |
            for file in ${ALL_CHANGED_FILES}; do
              echo "$file was changed"
            done
            file_count=$(echo ${ALL_CHANGED_FILES} | wc -w)
            echo $file_count
            if [ "${ALL_CHANGED_FILES_COUNT}" -ne 1 ]; then
              echo "Error: More than one file changed."
              exit 1
            fi
            if [[ ! $ALL_CHANGED_FILES =~ contributions\/(executable-tutorial|feedback|open-source)\/[\S]*-[\S]*\/README\.md$ ]]; then
              echo "Error: Not an async task"
              exit 1
            fi