name: Check task

on:
    pull_request_target:
      branches:
        - test_dir
      paths:
        - contributions/**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
  
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.event.pull_request.head.sha }}
        
        - name: Check file modifications
          run: gh pr view ${{ github.event.number }} --json files --jq '.files.[].path' | cat
          #with: 
          #  x:  ${{ github.event.number }}