name: Check task

on:
    pull_request_target:
      branches:
        - test_dir
      paths:
        - contributions/**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
  
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.event.pull_request.head.sha }}
        
        - name: Get changed files
          id: changed-files
          uses: tj-actions/changed-files@v45
  
        - name: Check added file
          env:
            ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
            ALL_CHANGED_FILES_COUNT: ${{ steps.changed-files.outputs.all_changed_files_count }}
          run: |
            for file in ${ALL_CHANGED_FILES}; do
              echo "Info: $file was changed"
            done
            if [ "${ALL_CHANGED_FILES_COUNT}" -ne 1 ]; then
              echo "Error: More than one file changed(${ALL_CHANGED_FILES_COUNT})"
              exit 1
            fi
            if [[ $ALL_CHANGED_FILES =~ ^contributions\/(executable-tutorial|feedback|open-source)\/[^\/]+\/README\.md$ ]]; then
              echo "Info: Matches async task"
            elif [[ $ALL_CHANGED_FILES =~ ^contributions\/(demo|presentation|scientific-paper)\/week[2-7]\/[^\/]+\/README\.md$ ]]; then
              echo "Info: Matches demo, presentation or scientific paper"
            else
              echo "Error: File in wrong directory($ALL_CHANGED_FILES)"
              exit 1
            fi